version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.0
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.8.0
    container_name: kibana

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.8.9
    container_name: logstash
    volumes:
      - ${PWD}/apache_logs:/tmp/apache_logs
      - ${PWD}/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ${PWD}/logstash/apache_template.json:/tmp/apache_template.json
